version: '3.4'

services:
    mssql:
        restart: always
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1433:1433"
        environment: 
            ACCEPT_EULA: Y
            SA_PASSWORD: Passw0rd123
            MSSQL_PID: Express